//IN ORDER TO PREVENT TYPO ERROR BETWEEN ACTION CREATOR AND REDUCER, WE SET VARIABLES
export const SET_USER = "SET_USER";
export const SET_TOKEN = "SET_TOKEN";
export const SET_PLAYLISTS = "SET_PLAYLISTS";
export const SET_DISCOVER_WEEKLY = "SET_DISCOVER_WEEKLY";
